global:
  scrape_interval: 5s

  external_labels:
    monitor: 'codebal-monitor'

scrape_configs:
  - job_name: 'courses_maximov'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:1111']