spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/courses_realm

server:
  port: 1111

keycloak:
  uri: 'http://localhost:8181/'
  realm: "courses_realm"
