spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/microservice_db
#    username: postgres
#    password: admin
#    url: jdbc:postgresql://localhost:5432/microservice_db1
    url: jdbc:postgresql://host.docker.internal:5432/microservice_db1
    username: admin
    password: password
    driver-class-na me: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://localhost:8181/realms/courses_realm
          issuer-uri: http://host.docker.internal:8181/realms/master
#          issuer-uri: http://localhost:8181/realms/master

server:
  port: 1111

keycloak:
  uri: 'http://host.docker.internal:8181/'
#  uri: 'http://localhost:8181/'
#  realm: "courses_realm"
  realm: "master"
