spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/microservice_db1
#    url: jdbc:postgresql://postgres:5432/microservice_db1
    url: jdbc:postgresql://host.docker.internal:5432/microservice_db1
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/master
server:
  port: ${SERVER_PORT:1111}

logging:
  level:
    root: INFO

keycloak:
  uri: 'http://localhost:8181/'
  realm: "master"

management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true